'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class EditInvoice

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''HFInvoiceHeaderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFInvoiceHeaderID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFMBNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFMBNO As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFMuatBarangDetailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFMuatBarangDetailID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFMode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModeItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModeItem As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFmuatBarangID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFmuatBarangID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFInvoiceDetailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFInvoiceDetailID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFTujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFTujuan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFIDDetailInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFIDDetailInvoice As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFNamakapal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFNamakapal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFNoInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFNoInvoice As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFPembayaran As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPaid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFTanggal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFTanggal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFCodeCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFCodeCust As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFNamaCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFNamaCust As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TxtNoInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoInvoice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtJenisBarang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJenisBarang As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtHargaInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHargaInvoice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtJenisPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJenisPembayaran As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DtInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DtInvoice As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''TxtHargaSatuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHargaSatuan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLKapal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLKapal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtTotalUkuran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTotalUkuran As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNamaCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNamaCustomer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtCodeCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCodeCustomer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtDaerahDitujukan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDaerahDitujukan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnTambah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnTambah As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Grid_Pilih_invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_Pilih_invoice As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''lInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linfoberhasil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linfoberhasil As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSimpan As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btBatal As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Grid_Invoice_Parent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_Invoice_Parent As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
