'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class QuotationPotential

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''PanelInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelInput As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PanelCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelCustomer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TxtNamaCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNamaCustomer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtAlamat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAlamat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLKotaASAlBarang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLKotaASAlBarang As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtkodearea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtkodearea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNoHP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNoHP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HfSo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HfSo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModeEdit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIDC As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PanelQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelQuotation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tb_tgl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_tgl As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lblQoNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQoNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLKotaTujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLKotaTujuan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtPenerima control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPenerima As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtJabatan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJabatan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLSatuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLSatuan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtHargaItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHargaItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_reset As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linfoberhasil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linfoberhasil As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelGrid As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Grid_SO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_SO As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''btSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSave As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btback As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''PanelView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelView As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Grid_SO_Parent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_SO_Parent As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''btn_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_new As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
