'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Sales_Quotation

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''tb_tgl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_tgl As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lblQoNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQoNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtCustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCustName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtCustCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCustCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLKotaTujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLKotaTujuan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtPenerima control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPenerima As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtJabatan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJabatan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLSatuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLSatuan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtHargaItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHargaItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtKeterangan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtKeterangan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_reset As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lblinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblinfoS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblinfoS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Grid_SO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_SO As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''btSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSave As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''DDLQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLQuotation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PanelApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelApprove As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Grid_SO_Parent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_SO_Parent As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''Panel_Close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Close As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Grid_Parent_Close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_Parent_Close As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''pnlbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlbutton As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hfQuotationClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfQuotationClose As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HfSo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HfSo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModeEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModeEdit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfClose As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfStatusClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfStatusClose As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIDC As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfItem As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFIDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFIDS As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfNamaCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNamaCustomer As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCodeCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCodeCustomer As Global.System.Web.UI.WebControls.HiddenField
End Class
