'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class KonfigurasiHeader

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''panelutama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelutama As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbljenis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljenis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbnama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbnama As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbdaerah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdaerah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAlamat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAlamat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNotelp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNotelp1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNoTelp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNoTelp2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbfax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbfax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbnoanggota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbnoanggota As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''uploadfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uploadfile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnupload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnupload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linfoberhasil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linfoberhasil As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSimpan As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btBatal As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''hfID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''GridViewHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewHeader As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''btcabang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btcabang As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panelcabang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelcabang As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlnamaperusahaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlnamaperusahaan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbdaerahcbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbdaerahcbg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbalamatcbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbalamatcbg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbtelp1cbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbtelp1cbg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbtelp2cbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbtelp2cbg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbtelp3cbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbtelp3cbg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbfaxcbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbfaxcbg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbemailcbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemailcbg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Linfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Linfo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Linfoberhasil2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Linfoberhasil2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btsavecbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btsavecbg As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''tbbatalcbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbbatalcbg As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Hfidcbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hfidcbg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfmodecbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfmodecbg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''GridViewHeadercbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewHeadercbg As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''btnkembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnkembali As Global.System.Web.UI.WebControls.Button
End Class
